Update changelog, add browser extension support
algolia/youtube-captions-scraper pull request #25
Opened 2023-11-16 16:48 UTC by Fiattarone

Love how the npm demo of this worked with the timestamp, but unfortunately in my current project, I'm not able to use axios at all (browser extensions do not support axios). Figured I'd throw a PR your way to use the classic fetch if the program decides it's inside of a browser extension. 

**Overview of changes:**

- Updated babel dev dependencies 
- Updated changelog
- Added two functions to index.js to determine if the current window type is a browser extension or not (left some room for the safari and firefox fellas, I'll tackle this later personally if no one else does) 

**_All ava tests passed before submitting this PR._**

Let me know if there's any additional considerations I should be making before this can merge with master, happy to help!

2023-11-17 09:11 UTC, Haroenv requested changes
looks great! but I think swapping the condition allows this fix to work for more than just in extensions

2023-11-17 09:11 UTC, Haroenv commented on src/index.js
> +  if (isRunningInExtension()) {
what about doing the other way round, and check if `fetch` exists, and fall back to axios in other cases (old node, old browser)?

2024-01-28 15:29 UTC, humphd commented
This would also allow using the module in a CloudFlare worker, which is also currently broken:

```
[wrangler:err] TypeError: adapter is not a function
    at dispatchRequest (file:///Users/humphd/repos/chatcraft.org/node_modules/.pnpm/axios@0.17.1/node_modules/axios/lib/core/dispatchRequest.js:59:10)
[wrangler:inf] GET /api/proxy 500 Internal Server Error (85ms)
```

I'd love to see `fetch()` be the default with fallback to `axios()` only if necessary.

2024-01-29 13:29 UTC, Haroenv approved these changes

2024-01-29 13:29 UTC, merged

2024-01-30 14:19 UTC, humphd commented
Thanks for this, works great in CloudFlare now!